version: '3'

services:
  scrapy:
    build: .
    container_name: crawler
    volumes:
      - .:/app
    tty: true
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
