version: '3'

services:
  scrapy:
    build: ./app
    command: scrapy-do -n scrapy-do --config ./scrapy-do.conf
    container_name: crawler
    ports:
      - "7654:7654"
    volumes:
      - ./app:/usr/src/app

  api:
    build: ./api/
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  front:
    container_name: frontend
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 8080:3000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql_conf:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
  
  minio:
    image: minio/minio
    volumes:
      - minio_data:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: accessKey
      MINIO_SECRET_KEY: secretKey
    command: server /export

volumes:
  minio_data:

