version: '3'

services:
  scrapy:
    build: .
    command: scrapy-do -n scrapy-do --config ./scrapy-do.conf
    container_name: crawler
    ports:
      - "7654:7654"
    volumes:
      - ./app:/usr/src/app
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql_conf:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
